-- =====================================================
-- AI FARMER CREDIT SCORER
-- DATABASE.SQL
-- =====================================================


-- =====================================================
-- 1. FARMERS TABLE
-- =====================================================

create table if not exists public.farmers (

    id bigint generated by default as identity primary key,

    full_name text not null,

    email text,

    phone text,

    location text,

    farm_type text,

    farm_size numeric,

    farm_income numeric,

    created_at timestamptz default now()

);


-- =====================================================
-- 2. FARMER ASSESSMENTS TABLE
-- =====================================================

create table if not exists public.farmer_assessments (

    id bigint generated by default as identity primary key,

    full_name text not null,

    email text not null,

    phone text not null,

    location text not null,

    farm_type text not null,

    farm_size numeric,

    farm_income numeric,

    income_frequency text,

    loan_amount numeric,

    loan_history text,

    monthly_expenses numeric,

    repayment_ability text,

    credit_score integer,

    credit_status text,

    created_at timestamptz default now()

);


-- =====================================================
-- 3. CONTACT MESSAGES TABLE
-- =====================================================

create table if not exists public.contact_messages (

    id bigint generated by default as identity primary key,

    full_name text not null,

    email text not null,

    message text not null,

    created_at timestamptz default now()

);


-- =====================================================
-- 4. ENABLE ROW LEVEL SECURITY
-- =====================================================

alter table public.farmers
enable row level security;

alter table public.farmer_assessments
enable row level security;

alter table public.contact_messages
enable row level security;


-- =====================================================
-- 5. INSERT POLICY FOR FARMERS
-- Allows website visitors to submit farmer information
-- =====================================================

create policy "Allow public farmer submissions"
on public.farmers
for insert
to anon
with check (true);


-- =====================================================
-- 6. INSERT POLICY FOR ASSESSMENTS
-- Allows website visitors to submit assessment forms
-- Does NOT allow public users to read all records.
-- =====================================================

create policy "Allow public assessment submissions"
on public.farmer_assessments
for insert
to anon
with check (true);


-- =====================================================
-- 7. INSERT POLICY FOR CONTACT MESSAGES
-- Allows website visitors to send messages.
-- =====================================================

create policy "Allow public contact messages"
on public.contact_messages
for insert
to anon
with check (true);


-- =====================================================
-- END
-- =====================================================
